# Laboratório Prático 2 - Dashboard Analítico de Vendas Globais

## Importando as bibliotecas

In [1]:
#install
#!pip install -q -U duckdb matplotlib numpy pandas plotly scikit-learn scipy seaborn shap statsmodels xgboost

In [2]:
#imports
import pandas as pd
import numpy as np
import os

## Acessando os dados

In [3]:
pasta_com_arquivos = '1-datasets/'
for nome_do_arquivo in os.listdir(pasta_com_arquivos):
    caminho_do_arquivo = os.path.join(pasta_com_arquivos, nome_do_arquivo)
    variavel_nome = nome_do_arquivo.replace('.csv','').replace('-','_').replace(' ','_')
    try:
        globals()[f'dataset_{variavel_nome}'] = pd.read_csv(caminho_do_arquivo)
    except Exception as e:
        print(f'Falha no carregamento no arquivo {nome_do_arquivo}: {e}')

Falha no carregamento no arquivo Produtos.csv: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

In [10]:
dataset_Clientes_clear.head(1)

,ID Cliente,Nome Cliente,Segmento,Cidade,Estado,Pais,Mercado,Regiao
0,RH-19495,Rick Hansen,Consumidor,New York City,New York,United States,US,East

In [14]:
dataset_Clientes_clear.columns

Index(['ID Cliente', 'Nome Cliente', 'Segmento', 'Cidade', 'Estado', 'Pais',
       'Mercado', 'Regiao'],
      dtype='str')

In [11]:
dataset_Pedidos_clear.head(1)

        ID Pedido Data Pedido  Data Envio Modo Envio Prioridade Pedido
0  CA-2012-124891  31-07-2012  31-07-2012  Mesmo Dia           Critico

In [15]:
dataset_Pedidos_clear.columns

Index(['ID Pedido', 'Data Pedido', 'Data Envio', 'Modo Envio',
       'Prioridade Pedido'],
      dtype='str')

In [ ]:
dataset_Produtos_clear.head(1)

,ID Produto,Categoria,SubCategoria,Nome Produto
0,TEC-AC-10003033,Tecnologia,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...

In [16]:
dataset_Produtos_clear.columns

Index(['ID Produto', 'Categoria', 'SubCategoria', 'Nome Produto'], dtype='str')

In [13]:
dataset_Vendas_clear.head(1)

,Pedido,Cliente,Produto,Valor Venda,Quantidade Vendida,Custo Envio
0,CA-2012-124891,RH-19495,TEC-AC-10003033,2309.65,7,933.57

In [17]:
dataset_Vendas_clear.columns

Index(['Pedido', 'Cliente', 'Produto', 'Valor Venda', 'Quantidade Vendida',
       'Custo Envio'],
      dtype='str')